### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by SuperNickyP** [StapleButter/blargSnes#33]

**Comment by DiscostewSM** [comment]
I will be honest here. Don't expect much from blargSNES until there's something announced that even I am in the dark about. I personally am doing a few things with it, but at a very slow pace because of other obligations. StapleButter has things he's doing as well. With n3DS being at the forefront of handheld homebrew (with retroArch builds satiating the thirst for SNES emulation), most are moving on to that upgrade, giving less of a reason to poke around with something for the o3DS and emulation.

The source code is here to fork for anyone that wants to tackle it, to improve it, etc.
